### ISSUE TITLE
bugs under treeland env

### ISSUE THREAD

**Issue by ComixHe** [linuxdeepin/dtkdeclarative#249]
```[tasklist]
### Tasks
- [ ] RoundRectangle: no round corner
- [ ] CheckDelegate: icon lookup
- [ ] PopUp: no blur effect
```
